# Generated by Django 2.2.15 on 2021-05-12 17:07

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Senior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dp', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Seniorinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('sname', models.CharField(max_length=100, null=True)),
                ('senior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Senior')),
            ],
        ),
        migrations.CreateModel(
            name='imagegallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('im', cloudinary.models.CloudinaryField(max_length=255, verbose_name='imgallery')),
                ('desc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Seniorinfo')),
            ],
        ),
        migrations.CreateModel(
            name='awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myaward', models.CharField(max_length=100, null=True)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Seniorinfo')),
            ],
        ),
    ]
