# Generated by Django 2.2.15 on 2021-05-12 21:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seniorinfo',
            name='pic',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='pic'),
        ),
    ]
