# Generated by Django 2.2.15 on 2021-05-13 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_seniorinfo_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate', models.IntegerField(default=10)),
                ('senior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Seniorinfo')),
            ],
        ),
    ]
