# Generated by Django 2.2.15 on 2021-05-13 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award', to='webapp.Seniorinfo'),
        ),
    ]
