# Generated by Django 2.2.15 on 2021-05-13 18:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20210513_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='awards',
            name='pict',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='pict'),
        ),
    ]
