# Generated by Django 2.2.15 on 2021-05-14 12:26

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_awards_pict'),
    ]

    operations = [
        migrations.CreateModel(
            name='fav_place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imag', cloudinary.models.CloudinaryField(max_length=255, verbose_name='imag')),
                ('description', models.CharField(max_length=1000, null=True)),
                ('place', models.CharField(max_length=20, null=True)),
                ('senior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favplace', to='webapp.Seniorinfo')),
            ],
        ),
    ]
