# Generated by Django 2.2.15 on 2021-05-15 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_fav_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, null=True)),
                ('author', models.CharField(max_length=15, null=True)),
                ('senior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='webapp.Seniorinfo')),
            ],
        ),
    ]
