# Generated by Django 2.2.15 on 2021-05-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='comment',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
